"use client";

import { useEffect, useRef, useState } from "react";
import { SignInLink } from "@/components/SignInLink";

/* Floating glass pill, not a white bar: the film shows around and through
   it, so the page reads as one surface from the first pixel.

   Cinema chrome rule: while the viewer scrolls DOWN through the film the
   pill retires upward so headlines and cards never collide with it; any
   scroll UP (or reaching the top) brings it straight back. Reduced motion
   keeps it parked permanently.

   Two things came out on 2026-07-28 in the deletion pass:

   - The mobile hamburger and its glass sheet. Every link behind it was an
     anchor on the page the visitor is already scrolling, plus a second copy
     of Add to Chrome, and the footer carries all four. On phones the pill is
     now the wordmark and the one ask, which is what the pill is for.
   - Sign in. It sat next to the primary CTA above the fold, competing with
     it for an audience that by definition does not have an account yet.
     /login is still reached from the #close section. */
export function Header() {
  const [hidden, setHidden] = useState(false);
  const lastY = useRef(0);

  useEffect(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    lastY.current = window.scrollY;
    const onScroll = () => {
      const y = window.scrollY;
      const dy = y - lastY.current;
      /* ignore sub-jitter deltas so Lenis easing can't flicker the pill */
      if (Math.abs(dy) < 6) return;
      lastY.current = y;
      if (y < 120) {
        setHidden(false);
        return;
      }
      /* the last viewport is the close CTA + footer: the pill stays retired
         there so it never decapitates the finale headline (Lenis's settle
         corrections otherwise re-show it at the exact bottom) */
      const max = document.documentElement.scrollHeight - window.innerHeight;
      if (max > 600 && y > max - 160) {
        setHidden(true);
        return;
      }
      setHidden(dy > 0);
    };
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  return (
    <header
      className={`fixed inset-x-0 top-3 z-30 px-3 transition-transform duration-300 ease-out sm:top-4 sm:px-6 ${
        hidden ? "-translate-y-[130%]" : "translate-y-0"
      }`}
    >
      <div className="rq-glass mx-auto flex max-w-5xl items-center justify-between rounded-full py-2 pl-4 pr-2">
        <a href="/" className="flex min-h-[44px] items-center gap-2">
          {/* The official mark (public/brand/litos-mark.svg), generated by
              scripts/generate-brand-assets.mjs: one drawing, black stack on
              white, everywhere the brand appears. */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/brand/litos-mark.svg" alt="" className="h-6 w-6" />
          <span className="text-base font-medium tracking-tight text-ink">
            Litos
          </span>
        </a>
        <nav className="hidden items-center gap-7 text-sm text-muted sm:flex">
          <a href="/#product" className="transition-colors hover:text-ink">
            Product
          </a>
          <a href="/browse-jobs" className="transition-colors hover:text-ink">
            Jobs
          </a>
          <a href="/try" className="transition-colors hover:text-ink">
            Try it free
          </a>
          {/* The "Pricing" link was REMOVED 2026-07-30, with the homepage
              #pricing section it pointed at. It has to go: an anchor pointing
              at no id fails tests/route-integrity.test.mjs.

              What it was here for, if pricing ever comes back: price belongs in
              the nav, not only in a section someone has to scroll past the film
              to reach. Six of ten competitors have no fetchable pricing page at
              all, and being the exception is only worth anything if it is
              findable. */}
          <a href="/#faq" className="transition-colors hover:text-ink">
            FAQ
          </a>
        </nav>
        <div className="flex items-center gap-2">
          {/* Color v1.1: action blue repeats on every true CTA. With Sign in
              gone this is the only control in the pill, which is the point. */}
          {/* Was "Add to Chrome" pointing at the store. The install ask now
              lives once, in #packet, beside the demo of the extension doing
              the work; the header carries the account instead, which is the
              one door that also opens on a phone. Deliberately NOT relabelled
              "Sign in": the pill is still the only control up here, and it has
              to read as an invitation to people who have no account yet. The
              returning-user door is the same one, and /login says "Create
              account" and "Look around without signing up" on arrival. */}
          <SignInLink
            source="header"
            className="inline-flex min-h-[44px] items-center rounded-full bg-brand px-3.5 py-2 text-[13px] font-medium text-white transition-opacity hover:opacity-90 sm:px-4 sm:text-sm"
          >
            Get started
          </SignInLink>
        </div>
      </div>
    </header>
  );
}
