export const TIKTOK_US_PIXEL_CODE = "DAA22IBC77U6VIRE3PD0";
export const TIKTOK_UAE_PIXEL_CODE = "DAA38C3C77UBCVGL0KRG";

export const TIKTOK_ADS_PIXEL_CODES = [
  TIKTOK_US_PIXEL_CODE,
  TIKTOK_UAE_PIXEL_CODE,
] as const;
